/* THIS FILE WAS GENERATED BY PAYLOAD. */
import type { Metadata } from "next";

import config from "@payload-config";
import { RootPage, generatePageMetadata } from "@payloadcms/next/views";
import { importMap } from "../importMap.js";

type Args = {
  params: Promise<{
    segments: string[];
  }>;
  searchParams: Promise<{
    [key: string]: string | string[];
  }>;
};

export const generateMetadata = (args: Args): Promise<Metadata> =>
  generatePageMetadata({
    config,
    params: args.params,
    searchParams: args.searchParams,
    importMap,
  });

const Page = (args: Args) =>
  RootPage({
    config,
    params: args.params,
    searchParams: args.searchParams,
    importMap,
  });

export default Page;
