/* THIS FILE WAS GENERATED BY PAYLOAD. */
import React from 'react'
import config from '@payload-config'
import { RootLayout } from '@payloadcms/next/layouts'

import './custom.css'

type Args = {
  children: React.ReactNode
}

const Layout = ({ children }: Args) => <RootLayout config={config}>{children}</RootLayout>

export default Layout
