/* THIS FILE WAS GENERATED BY PAYLOAD. */
/* DO NOT MODIFY IT BECAUSE IT COULD BE REWRITTEN AT ANY TIME. */
import React from 'react'

import './custom.css'

type Args = {
  children: React.ReactNode
}

const Layout = ({ children }: Args) => children

export default Layout
